// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sazhmqwcovckpbbzlqbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhemhtcXdjb3Zja3BiYnpscWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODc2MDAsImV4cCI6MjA2MjI2MzYwMH0.G_W3RV7AXt78bPr0H_CP2e5sH74CkFdVOvTgEakqzc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);